# Generated by Django 5.2.15 on 2026-06-21 14:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "System Admin"),
                            ("DEPT_HEAD", "Department Head"),
                            ("INSTRUCTOR", "Instructor"),
                        ],
                        default="INSTRUCTOR",
                        max_length=20,
                    ),
                ),
                (
                    "academic_rank",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GA", "Graduate Assistant"),
                            ("ASST_LECTURER", "Assistant Lecturer"),
                            ("LECTURER", "Lecturer"),
                            ("ASST_PROF", "Assistant Professor"),
                            ("ASSOC_PROF", "Associate Professor"),
                            ("PROF", "Professor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "overall_experience_years",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Total years of teaching experience. Set manually at first; once the system has run terms it can be recalculated automatically.",
                    ),
                ),
                (
                    "experience_auto_calculated",
                    models.BooleanField(
                        default=False,
                        help_text="Once true, overall_experience_years is maintained by the system instead of being edited by the department head.",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
