# Generated by Django 5.2.15 on 2026-06-21 14:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        ("institutions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1st choice"),
                            (2, "2nd choice"),
                            (3, "3rd choice"),
                        ]
                    ),
                ),
                (
                    "academic_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructor_preferences",
                        to="institutions.academicterm",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_by",
                        to="curriculum.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["rank"],
                "unique_together": {
                    ("instructor", "academic_term", "course"),
                    ("instructor", "academic_term", "rank"),
                },
            },
        ),
        migrations.CreateModel(
            name="PreferenceWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opens_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deadline", models.DateTimeField()),
                ("closed_manually", models.BooleanField(default=False)),
                (
                    "academic_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference_windows",
                        to="institutions.academicterm",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference_windows",
                        to="institutions.department",
                    ),
                ),
            ],
            options={
                "unique_together": {("department", "academic_term")},
            },
        ),
    ]
