# Generated by Django 5.2.15 on 2026-06-21 14:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "credit_hours",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=4
                    ),
                ),
                (
                    "lecture_hours",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=4
                    ),
                ),
                (
                    "tutorial_hours",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=4
                    ),
                ),
                (
                    "lab_hours",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=4
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("MAJOR", "Major Course"),
                            ("COMMON", "Common / Service Course"),
                            ("EXTENSION", "Extension Course"),
                        ],
                        default="MAJOR",
                        max_length=10,
                    ),
                ),
                (
                    "year_level",
                    models.PositiveSmallIntegerField(
                        help_text="Year of study this course targets, e.g. 1-5"
                    ),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Semester 1"), (2, "Semester 2"), (3, "Summer")],
                        default=1,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_courses",
                        to="institutions.department",
                    ),
                ),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True, related_name="dependents", to="curriculum.course"
                    ),
                ),
                (
                    "target_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Departments whose students take this course (besides the owning department).",
                        related_name="consumed_courses",
                        to="institutions.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department__code", "year_level", "code"],
            },
        ),
        migrations.CreateModel(
            name="StudentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_level", models.PositiveSmallIntegerField()),
                ("section", models.CharField(help_text="e.g. A, B, C", max_length=10)),
                ("number_of_students", models.PositiveIntegerField()),
                (
                    "is_extension",
                    models.BooleanField(
                        default=False,
                        help_text="Extension/evening program students, balanced separately from regular.",
                    ),
                ),
                (
                    "academic_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_groups",
                        to="institutions.academicterm",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_groups",
                        to="institutions.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department__code", "year_level", "section"],
                "unique_together": {
                    (
                        "department",
                        "academic_term",
                        "year_level",
                        "section",
                        "is_extension",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_term",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="institutions.academicterm",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="curriculum.course",
                    ),
                ),
                (
                    "student_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="curriculum.studentgroup",
                    ),
                ),
            ],
            options={
                "ordering": ["course__code", "student_group__section"],
                "unique_together": {("course", "student_group")},
            },
        ),
    ]
