# Generated by Django 5.2.15 on 2026-06-21 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="institution_logos/"
                    ),
                ),
                (
                    "max_major_courses_per_instructor",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="No instructor may be assigned more major courses than this in a term.",
                    ),
                ),
                (
                    "large_section_threshold",
                    models.PositiveSmallIntegerField(
                        default=35,
                        help_text="Sections with more students than this get doubled lab-hour load.",
                    ),
                ),
                ("weight_preference", models.FloatField(default=40.0)),
                ("weight_academic_rank", models.FloatField(default=20.0)),
                ("weight_overall_experience", models.FloatField(default=15.0)),
                ("weight_course_experience", models.FloatField(default=25.0)),
                (
                    "load_balance_penalty",
                    models.FloatField(
                        default=10.0,
                        help_text="How strongly the engine penalizes assigning more load to an already-loaded instructor. Higher = stronger load balancing.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Institution Settings",
                "verbose_name_plural": "Institution Settings",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "DEPT_HEAD"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_department",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AcademicTerm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(help_text="e.g. 2025/2026", max_length=20),
                ),
                (
                    "semester",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Semester 1"), (2, "Semester 2"), (3, "Summer")]
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="institutions.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-academic_year", "-semester"],
                "unique_together": {("institution", "academic_year", "semester")},
            },
        ),
    ]
