# Generated by Django 5.2.15 on 2026-06-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="previous_term_balance_weight",
            field=models.FloatField(
                default=10.0,
                help_text="How strongly the engine compensates for last semester's load when assigning this semester: instructors who were overloaded last semester get less this semester, and instructors who were under-loaded get more. 0 disables this.",
            ),
        ),
    ]
